using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace ImSee
{
    class Program
    {
        static void Main(string[] args)
        {

            Console.WriteLine("Loading....");
            Console.WriteLine("■□□□□□□□□□");
            Thread.Sleep(1000);
            Console.Clear();
            Console.WriteLine("Loading....");
            Console.WriteLine("■■□□□□□□□□");
            Thread.Sleep(1000);
            Console.Clear();
            Console.WriteLine("Loading....");
            Console.WriteLine("■■■□□□□□□□");
            Thread.Sleep(1000);
            Console.Clear();
            Console.WriteLine("Loading....");
            Console.WriteLine("■■■■□□□□□□");
            Thread.Sleep(1000);
            Console.Clear();
            Console.WriteLine("Loading....");
            Console.WriteLine("■■■■■□□□□□");
            Thread.Sleep(1000);
            Console.Clear();
            Console.WriteLine("Loading....");
            Console.WriteLine("■■■■■■□□□□");
            Thread.Sleep(1000);
            Console.Clear();
            Console.WriteLine("Loading....");
            Console.WriteLine("■■■■■■■□□□");
            Thread.Sleep(1000);
            Console.Clear();
            Console.WriteLine("Loading....");
            Console.WriteLine("■■■■■■■■□□");
            Thread.Sleep(1000);
            Console.Clear();
            Console.WriteLine("Loading....");
            Console.WriteLine("■■■■■■■■■□");
            Thread.Sleep(1000);
            Console.Clear();
            Console.WriteLine("Loading....");
            Console.WriteLine("■■■■■■■■■■");
            Thread.Sleep(1000);
            Console.Clear();
            Thread.Sleep(2000);
            Console.WriteLine("발사 준비 완료");
            Thread.Sleep(1000);
            Console.Clear();
            Console.WriteLine("발사 준비 완료, 카운트 다운");
            Thread.Sleep(2000);
            Console.Clear();
            Console.WriteLine("발사 버튼(엔터)을 눌러주세요.");
            Thread.Sleep(2000);
            Console.ReadLine();
            Console.Clear();
            Console.WriteLine("5...");
            Thread.Sleep(1000);
            Console.Clear();
            Console.WriteLine("4...");
            Thread.Sleep(1000);
            Console.Clear();
            Console.WriteLine("3...");
            Thread.Sleep(1000);
            Console.Clear();
            Console.WriteLine("2...");
            Thread.Sleep(1000);
            Console.Clear();
            Console.WriteLine("1...");
            Thread.Sleep(1000);
            Console.Clear();
            Console.WriteLine("0...");
            Thread.Sleep(2000);
            Console.Clear();
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■ ■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■   ■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■       ■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■         ■■■■■■■■■");
            Console.WriteLine("■■■■■■■           ■■■■■■■■");
            Thread.Sleep(500);
            Console.Clear();
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■ ■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■   ■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■       ■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■         ■■■■■■■■■");
            Console.WriteLine("■■■■■■■           ■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Thread.Sleep(500);
            Console.Clear();
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■ ■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■   ■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■       ■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■         ■■■■■■■■■");
            Console.WriteLine("■■■■■■■           ■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■   ■■■■■■■■■■■■");
            Thread.Sleep(500);
            Console.Clear();
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■ ■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■   ■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■       ■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■         ■■■■■■■■■");
            Console.WriteLine("■■■■■■■           ■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■   ■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■ ■■■■■■■■■■■■■");
            Thread.Sleep(500);
            Console.Clear();
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■ ■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■   ■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■       ■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■         ■■■■■■■■■");
            Console.WriteLine("■■■■■■■           ■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■   ■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■ ■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Thread.Sleep(500);
            Console.Clear();
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■ ■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■   ■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■       ■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■         ■■■■■■■■■");
            Console.WriteLine("■■■■■■■           ■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■   ■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■ ■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Thread.Sleep(500);
            Console.Clear();
            Console.WriteLine("■■■■■■■■■■■■ ■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■   ■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■       ■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■         ■■■■■■■■■");
            Console.WriteLine("■■■■■■■           ■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■   ■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■ ■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Thread.Sleep(500);
            Console.Clear();
            Console.WriteLine("■■■■■■■■■■■   ■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■       ■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■         ■■■■■■■■■");
            Console.WriteLine("■■■■■■■           ■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■     ■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■   ■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■ ■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Console.WriteLine("■■■■■■■■■■■■■■■■■■■■■■■■■■");
            Thread.Sleep(500);
            Console.Clear();
            Console.WriteLine("■ ■■■■■■■■     ■■ ■■ ■■ ■■");
            Console.WriteLine("■■■ ■■■■■■     ■ ■■■ ■■■■ ");
            Console.WriteLine(" ■■■■ ■■■■     ■■■ ■■ ■ ■■");
            Console.WriteLine("■■ ■■ ■ ■■     ■ ■■ ■■ ■■■");
            Console.WriteLine("■ ■■ ■ ■■       ■■■■ ■■■■■");
            Console.WriteLine("■ ■■ ■■■         ■■ ■ ■ ■■");
            Console.WriteLine("■ ■■ ■■           ■■■■■■■■");
            Console.WriteLine(" ■■■ ■ ■■■     ■■■ ■ ■■ ■■");
            Console.WriteLine("■■ ■■■■ ■■■   ■ ■■ ■■ ■■■■");
            Console.WriteLine("■ ■■ ■■■■■■■ ■■■■■■■■■■■■■");
            Console.WriteLine(" ■■■ ■■■■■■■■ ■■■ ■■■ ■■■■");
            Console.WriteLine("■■■ ■■■ ■■■■ ■■■■■■ ■■■■ ■");
            Console.WriteLine("■ ■■■■■ ■■■■■■■■  ■■■ ■■■■");
            Console.WriteLine(" ■■■ ■■ ■■ ■■■■■ ■■■■ ■■■ ");
            Console.WriteLine("■■ ■■ ■■■■■ ■■■ ■■■■ ■■■■ ");
            Thread.Sleep(500);
            Console.Clear();
            Console.WriteLine("■■  ■■■ ■      ■■■■  ■■■ ■");
            Console.WriteLine("■■   ■■ ■■     ■ ■ ■■■  ■■");
            Console.WriteLine(" ■ ■■  ■■■     ■■  ■■  ■■ ");
            Console.WriteLine("■ ■■  ■■■       ■ ■ ■■■  ■");
            Console.WriteLine(" ■■  ■ ■         ■■■  ■■■ ");
            Console.WriteLine(" ■■ ■■■           ■  ■■  ■");
            Console.WriteLine("  ■■■ ■ ■■     ■■■ ■■  ■■ ");
            Console.WriteLine(" ■■   ■■■■■   ■■ ■■  ■■ ■■");
            Console.WriteLine("■  ■   ■■■■■ ■■■  ■■  ■ ■■");
            Console.WriteLine("  ■■■ ■■ ■■ ■■■  ■■■■   ■■");
            Console.WriteLine("■   ■■  ■■■■■ ■ ■■  ■■ ■■ ");
            Console.WriteLine(" ■■ ■■ ■■ ■  ■■■■■ ■   ■■");
            Console.WriteLine("■■  ■■   ■■■ ■■■ ■  ■■■ ■ ");
            Console.WriteLine("■■  ■■ ■■  ■■■ ■■ ■■■   ■■");
            Console.WriteLine(" ■■ ■■  ■■■  ■■■ ■■■ ■■ ■ ");
            Thread.Sleep(500);
            Console.Clear();
            Console.WriteLine("■   ■■ ■ ■     ■■   ■■  ■■");
            Console.WriteLine("■  ■■   ■■     ■ ■  ■■   ■");
            Console.WriteLine(" ■   ■  ■       ■■  ■   ■ ");
            Console.WriteLine(" ■ ■ ■ ■         ■  ■■   ■");
            Console.WriteLine("  ■   ■           ■  ■■  ■");
            Console.WriteLine("■  ■    ■■     ■ ■ ■   ■ ■");
            Console.WriteLine("■  ■   ■  ■   ■   ■   ■  ■");
            Console.WriteLine(" ■ ■    ■  ■ ■   ■■  ■   ■");
            Console.WriteLine("■   ■■■   ■   ■    ■  ■  ■");
            Console.WriteLine("■ ■  ■■ ■    ■■   ■■  ■   ");
            Console.WriteLine("■    ■■   ■ ■ ■  ■   ■  ■ ");
            Console.WriteLine("■   ■  ■ ■ ■    ■■  ■■   ■");
            Console.WriteLine("  ■■   ■  ■ ■ ■   ■  ■  ■");
            Console.WriteLine("   ■■   ■   ■■ ■ ■■  ■   ■");
            Console.WriteLine("■  ■   ■■  ■■   ■  ■   ■■ ");
            Thread.Sleep(500);
            Console.Clear();
            Console.WriteLine("■      ■ ■     ■■    ■   ■");
            Console.WriteLine("■        ■     ■ ■       ■");
            Console.WriteLine(" ■              ■   ■   ■ ");
            Console.WriteLine(" ■     ■         ■       ■");
            Console.WriteLine("  ■               ■      ■");
            Console.WriteLine("■        ■     ■         ■");
            Console.WriteLine("   ■      ■   ■       ■   ");
            Console.WriteLine("   ■         ■       ■   ■");
            Console.WriteLine("      ■       ■       ■  ■");
            Console.WriteLine("  ■     ■     ■       ■   ");
            Console.WriteLine("■    ■■       ■         ■ ");
            Console.WriteLine("■          ■               ");
            Console.WriteLine("  ■■      ■       ■     ■");
            Console.WriteLine("        ■        ■   ■    ");
            Console.WriteLine("■  ■       ■■          ■  ");
            Thread.Sleep(500);
            Console.Clear();
            Thread.Sleep(2000);
            Console.WriteLine("7년전.");











        }
    }
}
